### ISSUE TITLE
Unable to update via the In-App updater

### ISSUE THREAD

**Issue by johnnyq** [YunoHost-Apps/itflow_ynh#28]
See here
![image](https://github.com/YunoHost-Apps/itflow_ynh/assets/1812594/fabaab61-c4b6-4c98-af23-fbc0218ab0b8)

ITFlow needs access to access to git to update the Application through the updater

**Comment by nietsmmar** [comment]
I am facing the same issue

**Comment by johnnyq** [comment]
@nietsmmar it looks like they regularly update the app but you still got to go to the updater page to update any new database Schema updates

**Comment by nietsmmar** [comment]
@johnnyq you mean the yunohost update page?

**Comment by OniriCorpe** [comment]
it's normal, the ynh don't use got to perform the installation

please, don't try to use the in-app updater since ynh handles the install and upgrade of this app

**Comment by johnnyq** [comment]
we should probably have a var in config.php that config_update_disable = 0 and the updater will not be shown if this is present

**Comment by OniriCorpe** [comment]
maybe but it's not listed here https://docs.itflow.org/config_php
